"""Add travel preferences to User model

Revision ID: 869c1019cb7f
Revises: 
Create Date: 2025-04-13 21:55:52.765315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869c1019cb7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('frequent_routes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('safety_preference', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('safety_preference')
        batch_op.drop_column('frequent_routes')
        batch_op.drop_column('home_location')

    # ### end Alembic commands ###
